{
 "title": "Openstack clouds canon",
 "description": "This dashboard visualizes data exporter by the Prometheus OpenStack Exporter:\r\nhttps://github.com/CanonicalLtd/prometheus-openstack-exporter",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cloud",
    "query": "openstack_exporter_cache_age_seconds"
   },
   {
    "name": "instance",
    "query": "openstack_exporter_cache_refresh_duration_seconds{cloud=\"$cloud\"}"
   },
   {
    "name": "swifthost",
    "query": "swift_disk_usage_bytes{type=\"used\",cloud=\"$cloud\"}"
   },
   {
    "name": "neutron_net",
    "label": "External networks",
    "query": "neutron_public_ip_usage{cloud=\"$cloud\",ip_type=\"routerip\"}"
   },
   {
    "name": "hypervisor",
    "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
   },
   {
    "name": "hypervisor_status",
    "query": "hypervisor_vcpus_total{cloud=\"$cloud\",hypervisor_hostname=\"$hypervisor\"}"
   },
   {
    "name": "aggregate",
    "label": "availability zone",
    "query": "hypervisor_vcpus_total{cloud=\"$cloud\"}"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "content": "# Openstack dashboard: $cloud\n\n* openstack data is cached for 5 minutes by default\n* \"Free IPs\" are not owned by any tenant and available for allocation\n* \"Unused IPs\" are owned by a tenant but not currently associated with an instance"
  },
  {
   "title": "Free IPs (provider)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(neutron_net_size{network_name=\"provider\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"provider\",cloud=\"$cloud\"})"
    }
   ]
  },
  {
   "title": "Free vCPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hypervisor_vcpus_total{cloud=\"$cloud\",nova_service_status=\"enabled\"})*sum(openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}) - sum(hypervisor_vcpus_used{cloud=\"$cloud\",nova_service_status=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Free disk",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 0 },
   "format": "gbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hypervisor_disk_gbs_total{cloud=\"$cloud\",nova_service_status=\"enabled\"}) * sum(openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) - sum(hypervisor_disk_gbs_used{cloud=\"$cloud\",nova_service_status=\"enabled\"})"
    }
   ]
  },
  {
   "title": "Unused IPs (provider)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(neutron_net_size{network_name=\"provider\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"provider\",cloud=\"$cloud\",ip_status=\"ACTIVE\"})) - (sum(neutron_net_size{network_name=\"provider\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"provider\",cloud=\"$cloud\"}))"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(hypervisor_memory_mbs_total{cloud=\"$cloud\"}) * sum(openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}) - sum(hypervisor_memory_mbs_used{cloud=\"$cloud\",nova_service_status=\"enabled\"}))"
    }
   ]
  },
  { "title": "KPI graphs - 14 days", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Free production floating IPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(neutron_net_size{network_name=\"provider\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"provider\",cloud=\"$cloud\"})",
     "legendFormat": "free ip of network \"provider\""
    },
    {
     "expr": "sum(neutron_net_size{network_name=\"public\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"public\",cloud=\"$cloud\"})",
     "legendFormat": "free ip of network \"public\""
    }
   ]
  },
  {
   "title": "Schedulable cpu2-ram4-disk20 instances",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(hypervisor_schedulable_instances{cloud=\"$cloud\",nova_service_status=\"enabled\"}) by (aggregate)",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Time until compute full",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "hypervisor_schedulable_instances:sum:by_cloud_status{cloud=\"$cloud\",nova_service_status=\"enabled\"} / -deriv(hypervisor_schedulable_instances:sum:by_cloud_status{cloud=\"$cloud\",nova_service_status=\"enabled\"}[14d]) >0"
    }
   ]
  },
  { "title": "Neutron", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Neutron agents up",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "Neutron agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 22 },
   "targets": [
    { "expr": "openstack_neutron_agent_state" }
   ]
  },
  {
   "title": "Neutron agents down",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(openstack_neutron_agent_state{adminState=\"up\"})-sum(openstack_neutron_agent_state{adminState=\"up\"})"
    }
   ]
  },
  {
   "title": "IPs in $neutron_net",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "repeat": "neutron_net",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",cloud=\"$cloud\"})",
     "legendFormat": "Floating IPs"
    },
    {
     "expr": "sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"routerip\",cloud=\"$cloud\"})",
     "legendFormat": "Router IPs"
    },
    {
     "expr": "sum(neutron_net_size{network_name=\"$neutron_net\",cloud=\"$cloud\"}) - sum(neutron_public_ip_usage{subnet_name=\"$neutron_net\",cloud=\"$cloud\"})",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Tenants with unused IPs in $neutron_net",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "repeat": "neutron_net",
   "targets": [
    {
     "expr": "neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\", ip_status=\"DOWN\",tenant=~\".+\",cloud=\"$cloud\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Tenants using most IPs in $neutron_net",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
   "repeat": "neutron_net",
   "targets": [
    {
     "expr": "topk(10, neutron_public_ip_usage{subnet_name=\"$neutron_net\",ip_type=\"floatingip\",tenant=~\".+\",cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Nova agent status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "openstack_nova_agent_state{adminState=\"enabled\"}"
    }
   ]
  },
  {
   "title": "CPU Overcommit ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}",
     "legendFormat": "Openstack CPU allocation ratio"
    }
   ]
  },
  {
   "title": "RAM Overcommit ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}",
     "legendFormat": "RAM allocation ratio"
    }
   ]
  },
  {
   "title": "Disk Overcommit ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 58 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}",
     "legendFormat": "Disk Overcommit ratio"
    }
   ]
  },
  {
   "title": "Free vCPUs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(hypervisor_vcpus_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}) by(aggregate)) - (sum(hypervisor_vcpus_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(hypervisor_disk_gbs_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) by(aggregate)) - (sum(hypervisor_disk_gbs_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "(sum(hypervisor_memory_mbs_total{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}) by(aggregate)) - (sum(hypervisor_memory_mbs_used{aggregate=~\".+\",cloud=\"$cloud\",nova_service_status=\"enabled\"}) by(aggregate))",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(hypervisor_running_vms{aggregate=~\".+\",cloud=\"$cloud\"}) by (aggregate)",
     "legendFormat": "{{aggregate}}"
    }
   ]
  },
  {
   "title": "Free vCPU per host ($aggregate)",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "(hypervisor_vcpus_total{cloud=\"$cloud\",aggregate=~\"$aggregate\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"vcpu\"}) - on(cloud,hypervisor_hostname,nova_service_status) hypervisor_vcpus_used{cloud=\"$cloud\",aggregate=~\"$aggregate\"}",
     "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
    }
   ]
  },
  {
   "title": "Free RAM GBs per host ($aggregate)",
   "type": "table",
   "gridPos": { "h": 5, "w": 7, "x": 9, "y": 71 },
   "targets": [
    {
     "expr": "((hypervisor_memory_mbs_total{cloud=\"$cloud\",aggregate=~\"$aggregate\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"ram\"}) - on(cloud,hypervisor_hostname,nova_service_status) hypervisor_memory_mbs_used{cloud=\"$cloud\",aggregate=~\"$aggregate\"}) / 1024",
     "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
    }
   ]
  },
  {
   "title": "Free disk GBs per host ($aggregate)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 71 },
   "targets": [
    {
     "expr": "(hypervisor_disk_gbs_total{cloud=\"$cloud\",aggregate=~\"$aggregate\"} * on(cloud) group_left openstack_allocation_ratio{cloud=\"$cloud\",resource=\"disk\"}) - on(cloud,hypervisor_hostname,nova_service_status) hypervisor_disk_gbs_used{cloud=\"$cloud\",aggregate=~\"$aggregate\"}",
     "legendFormat": "{{hypervisor_hostname}} ({{nova_service_status}})"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "Instances in ERROR state",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "nova_instances{instance_state=\"ERROR\",cloud=\"$cloud\"}",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top disk users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "gbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_resources_disk_gbs{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top RAM users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_resources_ram_mbs{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top vCPU users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_resources_vcpus{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Top instance owners",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10, nova_instances{cloud=\"$cloud\"})",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Openstack Exporter Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "Cache age",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "openstack_exporter_cache_age_seconds{cloud=\"$cloud\"}",
     "legendFormat": "Cache age"
    }
   ]
  },
  {
   "title": "Cache refresh duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "openstack_exporter_cache_refresh_duration_seconds{cloud=\"$cloud\"}",
     "legendFormat": "Refresh duration"
    }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=\"$instance\"}",
     "legendFormat": "Scrape duration"
    }
   ]
  }
 ]
}